### ISSUE TITLE
Debug will not start

### ISSUE THREAD

**Issue by nbkgit** [tht13/Python-vscode#51]
Issue Type: <b>Bug</b>

The python debugger will not start(see mkv video in file).
[2020-05-26 02-11-34.zip](https://github.com/tht13/Python-vscode/files/4684431/2020-05-26.02-11-34.zip)
When i want run Run and Debug, a ribbon appears for a split second and then disappears. Running python with or without debugging also doesn't start.

i try to debug a python program with installed python 3.82 64 bit and i installed all the in vs code recommended extensions, or if need be some other.

the python program is a simple mysql.connector program that gets a table and print its elements. i opened another python program but it doesn't matter.

Visual Studio code has only one problem reported here https://github.com/MicrosoftDocs/intellicode/issues/196

I first posted my problem here https://github.com/microsoft/vscode/issues/98449 ,but i was referred here.

Extension version: 0.2.3
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 430  @ 2.27GHz (4 x 2261)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

installed Extensions
PS C:\Users\Pedro\Desktop> code --list-extensions | % { "code --install-extension $_" }
code --install-extension abusaidm.html-snippets
code --install-extension bajdzis.vscode-database
code --install-extension batisteo.vscode-django
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.python-extension-pack
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension humao.rest-client
code --install-extension liximomo.sftp
code --install-extension magicstack.MagicPython
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.notepadplusplus-keybindings
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension mtxr.sqltools
code --install-extension ritwickdey.LiveServer
code --install-extension tht13.python
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WallabyJs.quokka-vscode
code --install-extension wholroyd.jinja

**Comment by nbkgit** [comment]
I found the error log maybe, this will help things a long
[2020-05-28 01:36:32.484] [exthost] [info] extension host started
[2020-05-28 01:36:32.776] [exthost] [info] ExtensionService#_doActivateExtension vscode.python {"startup":false,"extensionId":{"value":"vscode.python","_lower":"vscode.python"},"activationEvent":"onLanguage:python"}
[2020-05-28 01:36:32.778] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/python/dist/pythonMain
[2020-05-28 01:36:32.790] [exthost] [info] ExtensionService#_doActivateExtension batisteo.vscode-django {"startup":false,"extensionId":{"value":"batisteo.vscode-django","_lower":"batisteo.vscode-django"},"activationEvent":"onLanguage:python"}
[2020-05-28 01:36:32.790] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/batisteo.vscode-django-0.20.0/out/extension
[2020-05-28 01:36:32.842] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"extensionId":{"value":"ms-python.python","_lower":"ms-python.python"},"activationEvent":"onLanguage:python"}
[2020-05-28 01:36:32.842] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/ms-python.python-2020.5.80290/out/client/extension
[2020-05-28 01:36:32.845] [exthost] [info] ExtensionService#_doActivateExtension tht13.python {"startup":false,"extensionId":{"value":"tht13.python","_lower":"tht13.python"},"activationEvent":"onLanguage:python"}
[2020-05-28 01:36:32.845] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/tht13.python-0.2.3/out/client/src/pythonMain
[2020-05-28 01:36:32.937] [exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode {"startup":false,"extensionId":{"value":"VisualStudioExptTeam.vscodeintellicode","_lower":"visualstudioexptteam.vscodeintellicode"},"activationEvent":"onLanguage:python"}
[2020-05-28 01:36:32.938] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.7/dist/intellicode
[2020-05-28 01:36:33.170] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-05-28 01:36:33.170] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-05-28 01:36:33.183] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-05-28 01:36:33.184] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/emmet/dist/extension
[2020-05-28 01:36:33.278] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.git","_lower":"vscode.git"},"activationEvent":"*"}
[2020-05-28 01:36:33.278] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/git/dist/main
[2020-05-28 01:36:33.474] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":true,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"*"}
[2020-05-28 01:36:33.475] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/github-authentication/dist/extension.js
[2020-05-28 01:36:33.517] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-05-28 01:36:33.517] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/merge-conflict/dist/extension
[2020-05-28 01:36:33.530] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-05-28 01:36:33.531] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/search-result/dist/extension.js
[2020-05-28 01:36:33.535] [exthost] [info] ExtensionService#_doActivateExtension vscode.vscode-account {"startup":true,"extensionId":{"value":"vscode.vscode-account","_lower":"vscode.vscode-account"},"activationEvent":"*"}
[2020-05-28 01:36:33.535] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/vscode-account/dist/extension.js
[2020-05-28 01:36:33.569] [exthost] [info] ExtensionService#_doActivateExtension bajdzis.vscode-database {"startup":true,"extensionId":{"value":"bajdzis.vscode-database","_lower":"bajdzis.vscode-database"},"activationEvent":"*"}
[2020-05-28 01:36:33.569] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/bajdzis.vscode-database-2.2.0/out/extension.js
[2020-05-28 01:36:33.613] [exthost] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":true,"extensionId":{"value":"dbaeumer.vscode-eslint","_lower":"dbaeumer.vscode-eslint"},"activationEvent":"*"}
[2020-05-28 01:36:33.613] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/dbaeumer.vscode-eslint-2.1.5/client/out/extension
[2020-05-28 01:36:33.720] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":true,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"*"}
[2020-05-28 01:36:33.723] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/eamodio.gitlens-10.2.1/dist/extension
[2020-05-28 01:36:33.892] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":true,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"*"}
[2020-05-28 01:36:33.892] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/esbenp.prettier-vscode-4.7.0/dist/extension
[2020-05-28 01:36:33.894] [exthost] [info] ExtensionService#_doActivateExtension mtxr.sqltools {"startup":true,"extensionId":{"value":"mtxr.sqltools","_lower":"mtxr.sqltools"},"activationEvent":"*"}
[2020-05-28 01:36:33.894] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/mtxr.sqltools-0.21.8/extension.js
[2020-05-28 01:36:33.977] [exthost] [info] ExtensionService#_doActivateExtension ritwickdey.LiveServer {"startup":true,"extensionId":{"value":"ritwickdey.LiveServer","_lower":"ritwickdey.liveserver"},"activationEvent":"*"}
[2020-05-28 01:36:33.977] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/ritwickdey.liveserver-5.6.1/out/src/extension
[2020-05-28 01:36:35.381] [exthost] [info] ExtensionService#_doActivateExtension WallabyJs.quokka-vscode {"startup":true,"extensionId":{"value":"WallabyJs.quokka-vscode","_lower":"wallabyjs.quokka-vscode"},"activationEvent":"*"}
[2020-05-28 01:36:35.381] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Pedro/.vscode/extensions/wallabyjs.quokka-vscode-1.0.290/index
[2020-05-28 01:36:35.387] [exthost] [error] Activating extension ms-python.python failed due to an error:
[2020-05-28 01:36:35.393] [exthost] [error] Error: Cannot find module 'c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension'
Require stack:
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:33:115)
	at h._loadCommonJSModule (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:926:266)
	at h._doActivateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:822:856)
	at h._activateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:821:937)
	at Object.actualActivateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:883)
	at e._activateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:859)
	at c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:537
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:525)
	at e.activateByEvent (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:596:14)
	at h._activateByEvent (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:820:618)
	at c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:829:401
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-05-28 01:36:35.393] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2020-05-28 01:36:35.395] [exthost] [error] Error: Cannot find module 'c:\Users\Pedro\.vscode\extensions\esbenp.prettier-vscode-4.7.0\dist\extension'
Require stack:
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:33:115)
	at h._loadCommonJSModule (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:926:266)
	at h._doActivateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:822:856)
	at h._activateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:821:937)
	at Object.actualActivateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:883)
	at e._activateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:859)
	at c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:537
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:525)
	at e.activateByEvent (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:596:14)
	at h._activateByEvent (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:820:618)
	at h._handleEagerExtensions (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:824:542)
	at c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:828:123
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-05-28 01:36:35.395] [exthost] [error] Activating extension WallabyJs.quokka-vscode failed due to an error:
[2020-05-28 01:36:35.396] [exthost] [error] Error: Cannot find module 'c:\Users\Pedro\.vscode\extensions\wallabyjs.quokka-vscode-1.0.290\index'
Require stack:
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:33:115)
	at h._loadCommonJSModule (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:926:266)
	at h._doActivateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:822:856)
	at h._activateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:821:937)
	at Object.actualActivateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:883)
	at e._activateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:859)
	at c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:537
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:525)
	at e.activateByEvent (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:596:14)
	at h._activateByEvent (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:820:618)
	at h._handleEagerExtensions (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:824:542)
	at c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:828:123
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-05-28 01:36:38.026] [exthost] [info] eager extensions activated

**Comment by nbkgit** [comment]
In uninstalled and reinstalled the extension, but no changes. the other issue seems to be also because of the extension https://github.com/MicrosoftDocs/intellicode/issues/196

**Comment by nbkgit** [comment]
So furtehr invetsigation broad me to 
[2020-06-04 21:40:48.052] [exthost] [error] Activating extension ms-python.python failed due to an error:
[2020-06-04 21:40:48.053] [exthost] [error] Error: **Cannot find module './node_modules/diff-match-patch'**
Require stack:
- c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:271577)
	at n (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:186)
	at Object.<anonymous> (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:378528)
	at n (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:186)
	at Object.<anonymous> (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:68:75708)
	at n (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:186)
	at Object.<anonymous> (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:68:50415)
	at n (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:186)
	at Object.<anonymous> (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:68:8525)
	at n (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:186)
	at Object.<anonymous> (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:68:4679)
	at n (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:186)
	at Object.<anonymous> (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:933541)
	at n (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:186)
	at c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:985
	at Object.<anonymous> (c:\Users\Pedro\.vscode\extensions\ms-python.python-2020.5.80290\out\client\extension.js:1:996)
	at Module.o._compile (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:33:115)
	at h._loadCommonJSModule (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:926:266)
	at h._doActivateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:822:856)
	at h._activateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:821:937)
	at Object.actualActivateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:883)
	at e._activateExtension (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:859)
	at c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:537
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:525)
	at e.activateByEvent (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:596:14)
	at h._activateByEvent (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:820:618)
	at c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:829:401
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by nbkgit** [comment]
Found finally out i needed to copy the folders with content

> diff-match-patch
>vsls
>@jupyterlab

there where missing
 in `.vscode\extensions\ms-python.python-2020.5.80290\out\client\node_modules`

some i found in `.vscode\extensions\ms-python.python-2020.4.76186\out\client\node_modules`

Others like diff-match-patch after a google search
