### ISSUE TITLE
Since VS code update 1.46 extension will exit with error

### ISSUE THREAD

**Issue by nbkgit** [tht13/Python-vscode#53]
Quits with following error code
       TypeError: Cannot read property 'document' of undefined

System
Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Extensions

> Extension	                               Author (truncated)	Version
> html-snippets	                              abu                            0.2.1
> vscode-database	                      baj	                         2.2.0
> vscode-django	                      bat                              0.20.0
> vscode-eslint	                              dba                             2.1.5
> python-extension-pack	              don                            1.6.0
> xml	                                              Dot                              2.5.0
> gitlens	                                      eam                             10.2.2
> prettier-vscode	                      esb                              5.0.0
> vscode-firefox-debug	              fir                                 2.8.0
> rest-client	                              hum                            0.23.2
> sftp	                                              lix                                1.12.9
> MagicPython	                              mag                             1.1.0
> vscode-language-babel	               mgm                           0.0.27
> mssql	                                       ms-                            1.9.0
> python	                                       ms-                            2020.5.86806
> notepadplusplus-keybindings	ms-	                         1.0.5
> debugger-for-chrome	                 msj	                         4.12.8
> sqltools	                                         mtx	                 0.22.7
> LiveServer	                                 rit	                         5.6.1
> python	                                        tht	                         0.2.3
> vscodeintellicode	                        Vis	                        1.2.8
> quokka-vscode	                        Wal	                        1.0.294
> jinja	                                                 who	                0.0.8
> 

Error Message with stack trace in Extension log

[2020-06-11 01:34:31.356] [exthost] [error] Activating extension tht13.python failed due to an error:
[2020-06-11 01:34:31.357] [exthost] [error] TypeError: Cannot read property 'document' of undefined
	at PythonExtension.startServer (c:\Users\Pedro\.vscode\extensions\tht13.python-0.2.3\out\client\src\pythonMain.js:154:55)
	at activate (c:\Users\Pedro\.vscode\extensions\tht13.python-0.2.3\out\client\src\pythonMain.js:9:38)
	at Function._callActivateOptional (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:840:509)
	at Function._callActivate (c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:840:160)
	at c:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:838:960
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Promise.all (index 3)

**Comment by nbkgit** [comment]
Error goesn't appear after installing some updates.
